In [1]:
import pandas  as pd

In [2]:
df =pd.read_csv(r"C:\Users\nalin\Downloads\Salary_Data.csv")
df

,Age,Gender,Education Level,Job Title,Years of Experience,Salary
0,32.0,Male,Bachelor's,Software Engineer,5.0,90000.0
1,28.0,Female,Master's,Data Analyst,3.0,65000.0
2,45.0,Male,PhD,Senior Manager,15.0,150000.0
3,36.0,Female,Bachelor's,Sales Associate,7.0,60000.0
4,52.0,Male,Master's,Director,20.0,200000.0
...,...,...,...,...,...,...
6699,49.0,Female,PhD,Director of Marketing,20.0,200000.0
6700,32.0,Male,High School,Sales Associate,3.0,50000.0
6701,30.0,Female,Bachelor's Degree,Financial Manager,4.0,55000.0
6702,46.0,Male,Master's Degree,Marketing Manager,14.0,140000.0
6703,26.0,Female,High School,Sales Executive,1.0,35000.0

In [4]:
df.dropna()

,Age,Gender,Education Level,Job Title,Years of Experience,Salary
0,32.0,Male,Bachelor's,Software Engineer,5.0,90000.0
1,28.0,Female,Master's,Data Analyst,3.0,65000.0
2,45.0,Male,PhD,Senior Manager,15.0,150000.0
3,36.0,Female,Bachelor's,Sales Associate,7.0,60000.0
4,52.0,Male,Master's,Director,20.0,200000.0
...,...,...,...,...,...,...
6699,49.0,Female,PhD,Director of Marketing,20.0,200000.0
6700,32.0,Male,High School,Sales Associate,3.0,50000.0
6701,30.0,Female,Bachelor's Degree,Financial Manager,4.0,55000.0
6702,46.0,Male,Master's Degree,Marketing Manager,14.0,140000.0
6703,26.0,Female,High School,Sales Executive,1.0,35000.0

In [7]:
x=df.drop("Salary",axis=1)
y=df["Salary"]

In [8]:
y,x

(0        90000.0
 1        65000.0
 2       150000.0
 3        60000.0
 4       200000.0
           ...
 6699    200000.0
 6700     50000.0
 6701     55000.0
 6702    140000.0
 6703     35000.0
 Name: Salary, Length: 6704, dtype: float64,
        Age  Gender    Education Level              Job Title  \
 0     32.0    Male         Bachelor's      Software Engineer
 1     28.0  Female           Master's           Data Analyst
 2     45.0    Male                PhD         Senior Manager
 3     36.0  Female         Bachelor's        Sales Associate
 4     52.0    Male           Master's               Director
 ...    ...     ...                ...                    ...
 6699  49.0  Female                PhD  Director of Marketing
 6700  32.0    Male        High School        Sales Associate
 6701  30.0  Female  Bachelor's Degree      Financial Manager
 6702  46.0    Male    Master's Degree      Marketing Manager
 6703  26.0  Female        High School        Sales Executive

       Years of Experience
 0                     5.0
 1                     3.0
 2                    15.0
 3                     7.0
 4                    20.0
 ...                   ...
 6699                 20.0
 6700                  3.0
 6701                  4.0
 6702                 14.0
 6703                  1.0

 [6704 rows x 5 columns])

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_test =train_test_split(x,y,test_size=0.2,random_state =42)

In [ ]:
df.select_dtypes(include =['object'].columns
df=pd.get_dummies(df,drop_frist=true)

In [ ]:
x=df.drop ('Salary',axis=1)
y=df['Salary']
from sklearn.model_selection import train_test_split
X_train,X_test,Y_test =train_test_split(x,y,test_size=0.2,random_state =42)
from  sklearn.preprocessing import StandScaler 
scaler_x= StandardScaler()
scaler_y=StandardScaler()